### ISSUE TITLE
FEATURE: Submit a Poll Response

### ISSUE THREAD

**Issue by decant09** [decant09/love-running#1]
### USER STORY 1:
In order to **provide my opinion with regards a certain running topic or event** as a **user**, I can **select and submit an answer from the poll**

**Comment by decant09** [comment]
### USER STORY 2:
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response**

### Acceptance Criteria:

- The option should be provided as a checkbox
- The checkbox should be “checked” by default
- The option should appear next to the submit button
- After submitting the default submission confirmation should be adjusted to include the user name.

### Tasks:
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and show the name of the submitter
- [ ] Create a new field in the modal to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality

**Comment by decant09** [comment]
### USER STORY 3:
In order to **provide additional thoughts beyond the response options** as a **user**, I can **add a comment before I submit my poll response**
